export enum CartActions {
  ORDER_ASTEROID_ACTION = 'ORDER-ASTEROID-ACTION',
  REMOVE_ASTEROID_ORDER_ACTION = 'REMOVE-ASTEROID-ORDER-ACTION',
  SUBMIT_ORDER_ASTEROIDS_ACTION = 'SUBMIT-ORDER-ASTEROIDS-ACTION',
  GET_SAVED_ASTEROIDS_ORDER_ACTION = 'GET-SAVED-ASTEROIDS-ORDER-ACTION',
}
